embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  google:
    provider: "google"
    model_name: "models/gemini-2.5-pro"
    temperature: 0
    max_tokens: 2048

  groq_llama:
    provider: "groq"
    model_name: "llama-3.3-70b-versatile"
    temperature: 0
    max_tokens: 2048
    
  groq_gpt:
    provider: "groq"
    model_name: "openai/gpt-oss-120b"
    temperature: 0
    max_tokens: 2048